name: Generate Preview2

on:
  pull_request_target:
    types: [synchronize, reopened]

  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    
        
      # Find the PR associated with this push, if there is one.
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - run: echo "Your PR is ${PR_NUMBER}"
      env:
       PR_NUMBER: ${{ github.event.pull_request.number }}
    
    - uses: actions/checkout@v2
      with:
        ref: "refs/pull/${{ github.event.pull_request.number }}/merge"

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.6.1'
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: CI=false npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build
        
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.BOT }}
        publish_dir: ./build
        cname: ${{ github.event.pull_request.number }}.pr.blueedge.me
        external_repository: win11bot/pr-${{ github.event.pull_request.number }}
    
    - name: Sleep for 120 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
        
    - name: pr
      uses: mshick/add-pr-comment@v1
      env:
          BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.BOT }}
      with:
        message: |
            ✔️ Deploy Preview Updated! 
            🔍 Inspect the deploy log: ${{ env.BUILD_URL }}
            😎 Browse the preview: https://${{ github.event.pull_request.number }}.pr.blueedge.me !
        allow-repeats: true

  run-if-fail:
    if: ${{ always() && (needs.build.result=='failure'|| needs.deploy.result=='failure') }}
    needs: [build, deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Comment PR
      uses: unofficial-skills/actions-comment-pull-request@main
      with:
         message: |
              ❌ DEPLOY PREVIEW BUILD HAS FAILED 
         GITHUB_TOKEN: ${{ secrets.BOT }}
