# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  push:
    branches: [ test ]


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.6.1'

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: CI=false npm run build  
      
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: blueedge
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm,linux/arm/v6,linux/ppc64le,linux/s390x
          tags: blueedge/win11react:dev
          labels: ${{ steps.meta.outputs.labels }}
